#         ____ _                _    ____  _
#  _   _ / ___| |__   ___  ___ | |_ / ___|| |__   ___  _ __
# | | | | |   | '_ \ / _ \/ __|| __|\___ \| '_ \ / _ \| '_ \
# | |_| | |___| | | |  __/\__ \| |_  ___)| | | || (_)|| |_) |
#  \__, |\____|_| |_|\___||___/\__||____/|_| |_|\___/| .__/
#  |___/                                             |_|
#
# Discord: discord.ystoreplugins.com.br                                  
# Site: ystoreplugins.com.br                                  
#                                      

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _                    
#     /   \__ _| |_ __ _| |__   __ _ ___  ___ 
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#                                   
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Ativar o sistema de menu para comprar na loja
sign-buy-menu: true

# Quantia máxima de caracteres do nome do item da loja
max-item-characters: 20

# Traduzir nome dos itens padrões para português
translate-names: true

# Vender o inv inteiro usando o shift
shift-sell-all: true

# Rodar a task de limpeza de placas inexistentes após 5 segundos do load do servidor
shop-clear-task: true

# Ativar o sistema de bolsa (yBolsa, NextEconomy, StormEconomy e HeroBolsa)
bolsa: false

# Permitir os jogadores colocarem placas apenas no plot.
just-plot: false

# Preço máximo suportado na loja
# deixe 0 para não ter limite.
max-price: 0

# Tipo padrão da placa
# BUY - Players compram
# SELL - Players vendem
# BUYSELL - Playeres compram e vendem
default-type: 'SELL'

# Lore do ícone de selecionar item na configuração da placa
item-select-lore: [ '&aClique em um item do seu inventário para alterar' ]

# Ativar a troca do sistema de chat quando estiver no mohist
# compatível apenas com: UltimateChat, nChat e Legendchat
mohist-chat: false

# Sistema de holograma na loja de jogadores
sign-hologram:
  enabled: true
  hologram-buy:
    offset: 3.0
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&fLoja de &b{player}'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de compra: &b{price_buy} {provider_abbreviated}'
  hologram-sell:
    offset: 3.0
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&fLoja de &b{player}'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de venda: &b{price_sell} {provider_abbreviated}'
  hologram-buy-sell:
    offset: 3.5
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&fLoja de &b{player}'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de compra: &b{price_buy} {provider_abbreviated}'
      - '&fPreço de venda: &b{price_sell} {provider_abbreviated}'
  hologram-buy-admin:
    offset: 3.0
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&aLoja do Servidor'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de compra: &b{price_buy} {provider_abbreviated}'
  hologram-sell-admin:
    offset: 3.0
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&aLoja do Servidor'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de venda: &b{price_sell} {provider_abbreviated}'
  hologram-buy-sell-admin:
    offset: 3.5
    lines:
      - '{item_name}'
      - '[item][shopitem]'
      - '&aLoja do Servidor'
      - '&fQuantia comercializada: &b{amount}'
      - '&fEconomia utilizada: &b{provider}'
      - '&fPreço de compra: &b{price_buy} {provider_abbreviated}'
      - '&fPreço de venda: &b{price_sell} {provider_abbreviated}'

# Sistema de nomeação da placa
# Será identificado na primeira linha da placa
sign-definer:
  admin: 'lojaadmin'
  player: 'loja'

# Sistema de formatação da placa
sign-format:
  # Outras placeholder de preços: {price_buy_raw}, {price_sell_raw} (sem formatação de letra)
  buy: '&2C &r{price_buy} &7({provider_abbreviated})'
  sell: '&cV &r{price_sell} &7({provider_abbreviated})'
  buy-sell: '&2C &r{price_buy} | &cV &r{price_sell} &7({provider_abbreviated})'
  free: 'Grátis'
  sign:
    admin:
      line-1: '&aLoja Admin'
      line-2: '{format}'
      line-3: '{amount}'
      line-4: '&0Clique para ver' # placeholder {item_name} disponível
    player:
      line-1: '&a{owner}'
      line-2: '{format}'
      line-3: '{amount}'
      line-4: '&0Clique para ver' # placeholder {item_name} disponível

# Sistema de bônus
# Você pode criar quantos bônus quiser
# Será dado o bônus ao vender para a loja do servidor.
bonus:
  member:
    priority: 1
    # Permissão para ser reconhecido
    permission: 'ychestshop.bonus.member'
    # Quantia do bônus em %
    bonus: 10.0

# Sistema de descontos
# Você pode criar quantos descontos quiser
# Será dado o desconto ao comprar da loja do servidor.
discounts:
  member:
    priority: 1
    # Permissão para ser reconhecido
    permission: 'ychestshop.discount.member'
    # Quantia do desconto em %
    discount: 10.0

# Sistema de formatos de money e quantia
format:
  type: 'NUMBER' # Tipos: LETTER - NUMBER
  max-decimals: 4
  formats:
    - ''
    - ''
    - 'K'
    - 'M'
    - 'B'
    - 'T'
    - 'Q'
    - 'QQ'
    - 'S'
    - 'SS'
    - 'O'
    - 'N'
    - 'D'
